apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb-svc.yaml
  - mongodb-ss.yaml
  - ./network-policies/allow-color-api.yaml

labels:
  - pairs:
      app: mongodb
      project: gke-proj

configMapGenerator:
  - name: mongodb-init-colordb
    files:
      - mongo-init.js