apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - color-api.yaml
  - color-svc.yaml
  - ./network-policies/allow-external-access.yaml

labels:
  - pairs:
      app: color-api
      project: gke-proj